# 5.1 Advanced array indexing

# 5.2 view vs copy

In [2]:
import numpy as np

In [4]:
squid = np.arange(12).reshape(3, -1)
print(squid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
ward = squid[:, :2] # view - slices
print(ward)

[[0 1]
 [4 5]
 [8 9]]


In [9]:
sponge = squid[:, [0, 1]] #copy - accuracy
print(sponge)

[[0 1]
 [4 5]
 [8 9]]


In [11]:
sponge[0, 0] = 100
print(sponge)
print(squid)

[[100   1]
 [  4   5]
 [  8   9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
ward[0, 0] = 100
print(ward)
print(squid)

[[100   1]
 [  4   5]
 [  8   9]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [13]:
squid.__array_interface__

{'data': (38748832, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3, 4),
 'version': 3}

In [14]:
ward.__array_interface__

{'data': (38748832, False),
 'strides': (32, 8),
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3, 2),
 'version': 3}

In [15]:
sponge.__array_interface__

{'data': (50122864, False),
 'strides': (8, 24),
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3, 2),
 'version': 3}

In [17]:
np.shares_memory(squid, ward)

True

In [18]:
np.shares_memory(squid, sponge)

False

In [20]:
print(squid[:, :2].copy())

[[100   1]
 [  4   5]
 [  8   9]]
