# 2.1 Numpy array motivation

In [4]:
prices = []
N = 60*60*24*365
for i in range(N):
    prices.append(100 + i/100)
print(prices[:5])

[100.0, 100.01, 100.02, 100.03, 100.04]


In [5]:
avg = 0.0
for p in prices:
    avg += p/len(prices)
print(avg)

157779.995


In [2]:
import numpy as np

In [6]:
prices = 100 + np.arange(N)/100
print(prices[:5])

[100.   100.01 100.02 100.03 100.04]


In [8]:
avg = np.mean(prices)
print(avg)

157779.995


# 2.2 Numpy arrays basic

In [15]:
arr = np.array([10, 20, 30, 40, 50])

In [16]:
arr

array([10, 20, 30, 40, 50])

In [17]:
arr.ndim

1

In [18]:
arr.shape

(5,)

In [19]:
len(arr)

5

In [22]:
arr_2d = np.array([
    [10, 20 , 30 , 40, 50],
    [100, 200, 300, 400, 500]
])

In [24]:
print(arr_2d)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]


In [25]:
arr_2d.ndim

2

In [26]:
arr_2d.shape

(2, 5)

In [27]:
len(arr_2d)

2

In [28]:
arr_2d.size

10

In [29]:
type(arr_2d)

numpy.ndarray

In [31]:
arr_2d.dtype

dtype('int64')

In [33]:
print(np.array([1, 2, 3]))

[1 2 3]


In [34]:
print(np.array([1, True, 'e']))

['1' 'True' 'e']


In [35]:
foo = np.array([1, True, 'e'])
print(foo)

['1' 'True' 'e']


In [36]:
foo[0] = 'edededededededede'
print(foo)

['edededededededede' 'True' 'e']


In [40]:
a = np.array([
    [1, 2, 3, 4, 5],
    [5.5, 6.6, 7.7, 8.8, 9.9]
])
print(a)

[[1.  2.  3.  4.  5. ]
 [5.5 6.6 7.7 8.8 9.9]]


In [41]:
a = np.array([
    [1, 2, 3, 4, 5],
    [5.5, 6.6, 7.7, 8.8]
])
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# 2.3 Creating Numpy arrays

In [42]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [44]:
np.array(np.arange(24)).reshape(3, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [49]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
np.full(shape=(3, 5), fill_value='cat' )

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [56]:
np.arange(1, 17, 5)

array([ 1,  6, 11, 16])

In [58]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
np.random.randint(-5, 10, size=(2, 3) )

array([[ 4,  1, -4],
       [ 1, -3, -3]])

# 2.4 Indexing 1-D Arrays

In [62]:
foo = np.array([10 , 20 , 30 , 40, 50])
print(foo)

[10 20 30 40 50]


In [63]:
foo[0]

10

In [64]:
foo[1] = 99
print(foo)

[10 99 30 40 50]


In [66]:
foo[-1]

50

In [68]:
foo[[1, 2 ,4]]

array([99, 30, 50])

In [69]:
np.zeros(shape=3, dtype='int64')

array([0, 0, 0])

# 2.5 Indexing multidimentional arrays

In [77]:
a = np.array(np.arange(24)).reshape(3, -1)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [78]:
a[1,2]

10

In [79]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [87]:
a[:, [1]]

array([[ 1],
       [ 9],
       [17]])

In [84]:
a[1:3, [1, 3]]

array([[ 9, 11],
       [17, 19]])

# 2.6 Basic math

In [98]:
foo = np.array(np.arange(9)).reshape(3, -1)
bar = np.array(np.arange(9, 18)).reshape(3, -1)
print(foo)
print()
print(bar)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [99]:
foo + bar

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [100]:
foo - bar

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [101]:
foo / bar

array([[0.        , 0.1       , 0.18181818],
       [0.25      , 0.30769231, 0.35714286],
       [0.4       , 0.4375    , 0.47058824]])

In [102]:
foo * bar

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [103]:
foo @ bar

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [104]:
foo + np.full(shape=(3, 3), fill_value=5)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [105]:
foo+5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])