# 4.1 Where

In [1]:
import numpy as np

In [2]:
generator = np.random.default_rng()

In [3]:
foo = generator.integers(6, size=2*10**6)
print(foo)

[5 2 3 ... 5 0 4]


In [4]:
bar = generator.integers(6, size=2*10**6)
print(bar)

[4 0 5 ... 0 5 4]


In [9]:
%%timeit
baz = np.zeros(foo.size)
for i in range(foo.size):
    if bar[i] % 2 == 0:
        baz[i] = foo[i] * 2
    else:
        baz[i] = foo[i] /2

print(baz)

[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
676 ms ± 31.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%%timeit
boz = np.where(bar%2 == 0, foo*2, foo/2)
print(boz)

[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.   8. ]
[10.   4.   1.5 ... 10.   0.

In [8]:
np.array_equal(baz, boz)

True

# 4.2 Math functions

In [13]:
squee = np.array(np.random.random_integers(-5, 10, 9)).reshape(3, -1)
print(squee)

[[ 3 -1  3]
 [ 0  3  5]
 [ 4 10  3]]


/tmp/ipykernel_7403/2157175792.py:1: DeprecationWarning: This function is deprecated. Please call randint(-5, 10 + 1) instead
  squee = np.array(np.random.random_integers(-5, 10, 9)).reshape(3, -1)


In [14]:
np.sum(squee)

30

In [15]:
np.sum(squee, axis=0)

array([ 7, 12, 11])

In [16]:
np.sum(squee, axis=1)

array([ 5,  8, 17])

In [17]:
np.sum(squee, axis=0, keepdims=True)

array([[ 7, 12, 11]])

In [18]:
squee[0, 0] = np.nan
print(squee)
np.sum(squee, where=-np.isnan(squee))

ValueError: cannot convert float NaN to integer

In [19]:
np.sum(np.nan_to_num(squee))

30

In [20]:
np.nansum(squee)

30

# 4.3 Any() all()

In [21]:
foo = np.array([
    [np.nan, 4.4],
    [1.0, 3.2],
    [np.nan, np.nan],
    [0.1, np.nan]
])
print(foo)

[[nan 4.4]
 [1.  3.2]
 [nan nan]
 [0.1 nan]]


In [23]:
print(np.isnan(foo))

[[ True False]
 [False False]
 [ True  True]
 [False  True]]


In [27]:
mask = np.any(np.isnan(foo), axis=1)
print(mask)

[ True False  True  True]


In [25]:
np.all(np.isnan(foo), axis=1)

array([False, False,  True, False])

In [28]:
foo[mask]

array([[nan, 4.4],
       [nan, nan],
       [0.1, nan]])

# 4.4 Concatenate

In [30]:
a = np.zeros(shape=(3, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
b = np.ones(shape=(2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [32]:
np.concatenate((a, a, a), axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.concatenate((a, a, a), axis=1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.concatenate((a, b), axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [36]:
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

# 4.5 Stacking

In [37]:
foo = np.array(['a', 'b'])
bar = np.array(['c', 'd'])
baz = np.array(['e', 'f'])
bingo = np.array([['g', 'h', 'i']])
bongo = np.array(
    [['j', 'k'],
     ['i', 'm']]
)

In [39]:
np.vstack((foo, bar))

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [41]:
np.vstack((foo, bar, baz))

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [43]:
np.hstack((foo, bar))

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [45]:
np.hstack((foo, baz, bar))

array(['a', 'b', 'e', 'f', 'c', 'd'], dtype='<U1')

In [46]:
np.stack((foo, bar), axis=0)

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [47]:
np.stack((foo, bar), axis=1)

array([['a', 'c'],
       ['b', 'd']], dtype='<U1')

In [49]:
np.stack((foo, bar), axis=-2)

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

# 4.6 Sorting

In [52]:
foo = np.array(np.random.randint(-5, 10 , 10))
print(foo)

[ 8  7  4  6  2 -2  6  8 -3 -2]


In [53]:
np.sort(foo)

array([-3, -2, -2,  2,  4,  6,  6,  7,  8,  8])

In [54]:
foo

array([ 8,  7,  4,  6,  2, -2,  6,  8, -3, -2])

In [56]:
foo.sort()
foo

array([-3, -2, -2,  2,  4,  6,  6,  7,  8,  8])

In [57]:
bar = np.array([5, np.nan, 3, 11])
np.sort(bar)

array([ 3.,  5., 11., nan])

In [58]:
np.sort(bar)[::-1]

array([nan, 11.,  5.,  3.])

In [63]:
-np.sort(-bar)

array([11.,  5.,  3., nan])

In [64]:
boo = np.array(np.random.randint(-5, 10, 9)).reshape(3, -1)
print(boo)

[[ 9  7 -3]
 [ 8 -1 -4]
 [ 7 -5 -4]]


In [65]:
np.sort(boo, axis=0)

array([[ 7, -5, -4],
       [ 8, -1, -4],
       [ 9,  7, -3]])

In [66]:
np.sort(boo, axis=1)

array([[-3,  7,  9],
       [-4, -1,  8],
       [-5, -4,  7]])

In [67]:
boo[np.argsort(boo[:, 0])]

array([[ 7, -5, -4],
       [ 8, -1, -4],
       [ 9,  7, -3]])

# 4.7 Unique

In [68]:
gar = np.array(np.random.randint(-5 , 10, 10))
print(gar)

[ 5  4  3 -4  2 -2  0  3 -4  0]


In [70]:
np.unique(gar)

array([-4, -2,  0,  2,  3,  4,  5])

In [71]:
np.unique(gar, return_index=True)

(array([-4, -2,  0,  2,  3,  4,  5]), array([3, 5, 6, 4, 2, 1, 0]))

In [74]:
unique, first_position = np.unique(gar, return_index=True)
print(unique)
print(first_position)

[-4 -2  0  2  3  4  5]
[3 5 6 4 2 1 0]


In [75]:
unique[np.argsort(first_position)]

array([ 5,  4,  3, -4,  2, -2,  0])

In [76]:
np.unique(gar, return_counts=True)

(array([-4, -2,  0,  2,  3,  4,  5]), array([2, 1, 2, 1, 2, 1, 1]))