# 3.3 reshape

In [2]:
import numpy as np

In [3]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [4]:
a = a.reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a = a.reshape(3, -1)

In [6]:
b = a.T
print(b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 3.4 Boolean indexing

In [7]:
foo = np.array(np.random.randint(-5, 10, 9)).reshape(3,3)
print(foo)

[[-1  3  0]
 [ 1  3  5]
 [ 9 -1  0]]


In [8]:
mask = foo == 0

In [9]:
foo[mask] = -10
print(foo)

[[ -1   3 -10]
 [  1   3   5]
 [  9  -1 -10]]


In [10]:
foo > 0

array([[False,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

# 3.8 Nan

In [11]:
bot = np.ones((3, 4))
bot[[0, 2], [1, 2]] = np.nan
print(bot)

[[ 1. nan  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1. nan  1.]]


In [12]:
bot == np.nan

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [13]:
np.nan == np.nan

False

In [14]:
np.isnan(bot)

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

# 3.9 Infinity

In [15]:
a = np.array([np.inf, np.NINF, 2])
print(a)

[ inf -inf   2.]


In [16]:
np.isinf(a)

array([ True,  True, False])

In [17]:
a == np.NINF

array([False,  True, False])

# 3.10 Random

In [18]:
np.random.choice([1, 22, 3, 4, 3 , 23, 23])

23

In [19]:
np.random.uniform(1, 2, size=(2,2))

array([[1.65847859, 1.71342753],
       [1.7788865 , 1.55612171]])

In [20]:
np.random.normal(0, 1, size=2)

array([-0.05082472, -0.88898446])

In [21]:
np.random.binomial(10, 0.25, size = (2, 2))

array([[4, 2],
       [2, 5]])